package com.demax.core.domain.model

enum class BuildingTypeDomainModel {
    RESIDENTIAL,
    MEDICAL_INSTITUTION,
    EDUCATIONAL_INSTITUTION,
    SHOPPING_CENTER,
    OFFICE_BUILDING,
    TRANSPORTATION_INFRASTRUCTURE,
    WAREHOUSE_BUILDING,
    PARKING_LOT,
    RELIGIOUS_INSTITUTION,
    CULTURAL_INSTITUTION,
    CATERING_FACILITY,
    ENTERTAINMENT_COMPLEX,
    SPORTS_FACILITY,
    UNSPECIFIED,
}